image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [-490.0327,   0.      , 362.31954,
           0.     , -488.29911, 243.92284,
           0.     ,   0.      ,   1.      ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.013648, -0.119528, -0.013999, -0.025910, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [-1., 0.,  0.,
          0., -1., 0.,
          0., 0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [-464.54321,   0.      , 387.54648,   0.,
            0.     , -490.34637, 250.49215,   0.,
            0.     ,   0.      ,   1.     ,   0.     ]
