bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    default_bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"
    
    # Blackboard variables
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    path_blackboard_id: path
    
    plugin_lib_names:
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    current_goal_checker: "goal_checker"
    current_progress_checker: "progress_checker"
    odom_topic: "/odom"
    cmd_vel_topic: "/cmd_vel"
    transform_tolerance: 1.0
    enable_controller_plugin_verification: false
    controller_patience: 15.0
    max_controller_duration: 0.5
    enable_heartbeat: true
    heartbeat_interval: 0.25
    heartbeat_timeout: 15.0

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: -0.26
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_theta: 1.5
      vx_samples: 20
      vtheta_samples: 20
      sim_time: 2.0
      xy_goal_tolerance: 0.25
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
      visualize_potential: true

recoveries_server:
  ros__parameters:
    use_sim_time: false
    plugin_list: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
      min_spin_velocity: 0.4
    backup:
      plugin: "nav2_recoveries/BackUp"
      min_back_up_velocity: -0.1
      max_back_up_distance: 0.5
    wait:
      plugin: "nav2_recoveries/Wait"
      wait_time: 10.0

local_costmap:
  ros__parameters:
    use_sim_time: false
    update_frequency: 5.0
    global_frame: odom
    robot_base_frame: base_link
    plugins: ["voxel_layer", "inflation_layer"]

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: true
      z_resolution: 0.05
      scan:
        topic: /scan

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55

global_costmap:
  ros__parameters:
    use_sim_time: false
    update_frequency: 1.0
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      scan:
        topic: /scan

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      [
        "collision_monitor",
        "docking_server",
        "slam_toolbox",
        "planner_server",
        "controller_server",
        "recoveries_server",
        "bt_navigator",
        "local_costmap",
        "global_costmap",
      ]
    configure_timeout: 20.0
    activate_timeout: 10.0
    startup_timeout: 30.0
