# -----------------------------------------------------------------------------
# Behavior Tree Navigator
# -----------------------------------------------------------------------------
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.3
    default_bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"
    
    # Blackboard variables
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    path_blackboard_id: path
    
    # Uncomment or adjust as needed:
    # plugin_lib_names:
    #   - nav2_spin_action_bt_node
    #   - nav2_wait_action_bt_node
    #   - nav2_clear_costmap_service_bt_node
    #   - nav2_is_stuck_condition_bt_node
    #   - nav2_goal_reached_condition_bt_node
    #   - nav2_initial_pose_received_condition_bt_node
    #   - nav2_reinitialize_global_localization_service_bt_node
    #   - nav2_rate_controller_bt_node
    #   - nav2_distance_controller_bt_node
    #   - nav2_speed_controller_bt_node
    #   - nav2_recovery_node_bt_node
    #   - nav2_pipeline_sequence_bt_node
    #   - nav2_round_robin_node_bt_node
    #   - nav2_transform_available_condition_bt_node
    #   - nav2_time_expired_condition_bt_node
    #   - nav2_distance_traveled_condition_bt_node
    #   - nav2_single_trigger_bt_node

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

# -----------------------------------------------------------------------------
# Controller Server
# -----------------------------------------------------------------------------
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 8.0
    min_x_velocity_threshold: 0.05
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.2
    failure_tolerance: 1.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    current_goal_checker: "goal_checker"
    current_progress_checker: "progress_checker"
    odom_topic: "/odom"
    cmd_vel_topic: "/cmd_vel"
    transform_tolerance: 0.5
    enable_controller_plugin_verification: false
    controller_patience: 10.0
    max_controller_duration: 1.0
    enable_heartbeat: true
    heartbeat_interval: 0.1
    heartbeat_timeout: 5.0

    # Progress Checker
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 20.0

    # Goal Checker
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.25
      stateful: true

    # DWB Local Planner plugin configuration
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      # -----------------------------------------------------------------------
      # Velocity / Acceleration Limits
      # -----------------------------------------------------------------------
      min_vel_x: 0.0
      max_vel_x: 0.15        # Slow forward speed for controlled motion
      max_speed_xy: 0.2      # Combined XY speed cap
      min_vel_theta: -0.5
      max_vel_theta: 0.5
      acc_lim_x: 0.2         # Gentle linear acceleration
      decel_lim_x: -0.2      # Gentle linear deceleration
      acc_lim_theta: 0.3     # Gentle angular acceleration
      decel_lim_theta: -0.3  # Gentle angular deceleration
      min_speed_theta: 0.0   # Allow in-place rotation at slow speeds
      min_theta_velocity_threshold: 0.1

      # -----------------------------------------------------------------------
      # Trajectory Sampling
      # -----------------------------------------------------------------------
      vx_samples: 8
      vtheta_samples: 12
      sim_time: 2.0
      angular_granularity: 0.1

      # -----------------------------------------------------------------------
      # Distance / Goal Biases
      # -----------------------------------------------------------------------
      # These biases influence how much the controller prioritizes path-following
      # vs. heading directly to the goal.
      path_distance_bias: 32.0
      goal_distance_bias: 5.0
      goal_align_bias: 5.0

      # -----------------------------------------------------------------------
      # Critics
      # -----------------------------------------------------------------------
      critics: ["Oscillation", "BaseObstacle", "PathAlign", "GoalAlign"]

      # Adjust how strongly obstacles and path alignment are weighted
      BaseObstacle.scale: 0.01
      PathAlign.scale: 32.0
      GoalAlign.scale: 5.0

      # -----------------------------------------------------------------------
      # Oscillation and Stopping Tolerances
      # -----------------------------------------------------------------------
      oscillation_reset_dist: 0.5
      oscillation_reset_angle: 0.75
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 1.0
      trans_stopped_velocity: 0.1
      theta_stopped_velocity: 0.1

      # -----------------------------------------------------------------------
      # Additional Options
      # -----------------------------------------------------------------------
      prune_plan: true
      debug_trajectory_details: true
      publish_evaluation: true
      publish_global_plan: true
      publish_local_plan: true
      publish_trajectories: true
      publish_cost_grid_pc: true

# -----------------------------------------------------------------------------
# Planner Server
# -----------------------------------------------------------------------------
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 1.0
      use_astar: true
      allow_unknown: false
      visualize_potential: true
      lethal_cost: 253
      neutral_cost: 50
      scale: 3
      cost_factor: 3.0
      publish_potential: true
      use_quadratic: true
      orientation_mode: 0
      use_grid_path: true
      allow_diagonal: false
      use_dijkstra: false
      track_unknown_space: true

# -----------------------------------------------------------------------------
# Behavior Server
# -----------------------------------------------------------------------------
behavior_server:
  ros__parameters:
    use_sim_time: false
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_timeout: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
    enable_stamped_cmd_vel: true

# -----------------------------------------------------------------------------
# Local Costmap
# -----------------------------------------------------------------------------
local_costmap:
  ros__parameters:
    use_sim_time: false
    update_frequency: 5.0
    publish_frequency: 5.0
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 3
    height: 3
    resolution: 0.05
    footprint: "[[-0.17, -0.15], [-0.17, 0.15], [0.17, 0.15], [0.17, -0.15]]"
    footprint_padding: 0.05
    plugins: ["voxel_layer", "inflation_layer"]
    
    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: true
      publish_voxel_map: true
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 16
      max_obstacle_height: 2.0
      mark_threshold: 0
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: "LaserScan"
        raytrace_max_range: 2.0
        raytrace_min_range: 0.02
        obstacle_max_range: 1.5
        obstacle_min_range: 0.02
        inf_is_valid: false

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.4
      cost_scaling_factor: 5.0
      inflate_unknown: false
      inflate_around_unknown: true

# -----------------------------------------------------------------------------
# Global Costmap
# -----------------------------------------------------------------------------
global_costmap:
  ros__parameters:
    use_sim_time: false
    update_frequency: 2.0
    publish_frequency: 2.0
    global_frame: map
    robot_base_frame: base_link
    footprint: "[[-0.17, -0.15], [-0.17, 0.15], [0.17, 0.15], [0.17, -0.15]]"
    footprint_padding: 0.05
    resolution: 0.05
    track_unknown_space: true
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    always_send_full_costmap: true

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: "LaserScan"
        raytrace_max_range: 1.5
        raytrace_min_range: 0.05
        obstacle_max_range: 1.0
        obstacle_min_range: 0.05
        inf_is_valid: false

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
      enabled: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.4
      cost_scaling_factor: 5.0

# -----------------------------------------------------------------------------
# Collision Monitor (if in use)
# -----------------------------------------------------------------------------
collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    observation_sources: ["scan"]
    
    polygons: ["robot_footprint"]
    robot_footprint:
      type: "polygon"
      points: "[[-0.13, -0.13], [-0.13, 0.13], [0.13, 0.13], [0.13, -0.13]]"
      action_type: "stop"
      min_points: 3
      visualize: true
      enabled: true

    scan:
      type: "scan"
      topic: "/scan"
      min_height: 0.05
      max_height: 0.5
      obstacle_range: 0.5
      raytrace_range: 1.0
      observation_persistence: 0.0
      inf_is_valid: false
      marking: true
      clearing: true
      data_type: "LaserScan"

    stop_on_collision: true
    scan_obstacle_range: 0.4
    slowdown_radius: 0.3
    approach_velocity_scaling: 0.5
    collision_range: 0.2
    publish_rate: 10.0
    observation_points_per_scan: 2
    velocity_scaling_factor: 0.5
    min_velocity_scaling: 0.2
    footprint_topic: "/local_costmap/published_footprint"
    transform_tolerance: 0.5
