camera_frame_id: camera_link
lidar_frame_id: laser
target_frame_id: base_link

# Initial guess for transform (adjust these based on physical measurements)
initial_transform:
  translation:
    x: 0.0
    y: 0.0
    z: 0.18  # Height difference between LiDAR and camera
  rotation:
    roll: 3.14159  # 180° rotation around X axis (pi radians)
    pitch: 0.0
    yaw: 0.0 