slam_toolbox:
  ros__parameters:
    # Robot frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # SLAM mode
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_timeout: 0.2
    update_timing: true
    publish_period: 0.5
    map_update_interval: 5.0
    max_update_rate: 10.0

    # Map management
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05

    # Processing parameters
    process_near_pose: true
    use_scan_matching: true
    use_scan_barycenter: true
    # Increasing these slightly can help reduce rapid, small updates that may accumulate noise:
    minimum_travel_distance: 0.2    # increased from 0.1 m
    minimum_travel_heading: 0.2       # increased from 0.1 rad
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5



    # Loop closure parameters (added for improved consistency in smaller environments)
    do_loop_closing: true
    loop_search_space_dimension: 4.0        # reduced from larger defaults (e.g., 8.0 m) for smaller areas
    loop_search_space_resolution: 0.02        # finer resolution to improve matching in a compact space
    loop_search_space_smear_deviation: 0.05     # slight increase to allow for minor noise variations

    # (Optional) Coarse matching parameters – adjust if your environment is challenging:
    coarse_search_angle_offset: 0.349         # ~20° in radians
    coarse_angle_resolution: 0.0349           # ~2° in radians
    loop_match_minimum_response_coarse: 0.3     # example value; adjust as needed
