slam_toolbox:
  ros__parameters:
    # Robot frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # SLAM mode
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_timeout: 0.3    # increased from 0.2 to allow extra time for fast movements
    update_timing: true
    publish_period: 0.5
    map_update_interval: 0.5
    max_update_rate: 10.0

    # Map management
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05

    # Processing parameters
    process_near_pose: true
    use_scan_matching: true
    use_scan_barycenter: true
    # Lowering these thresholds to force more frequent updates during quick motions:
    minimum_travel_distance: 0.1    # reduced from 0.2 m
    minimum_travel_heading: 0.1       # reduced from 0.2 rad
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.15   # increased from 0.1 to filter out weak scan matches
    link_scan_maximum_distance: 2.0    # increased from 1.5 to accommodate larger displacements

    # Loop closure parameters (added for improved consistency in smaller environments)
    do_loop_closing: true
    loop_search_space_dimension: 4.0        # reduced from larger defaults (e.g., 8.0 m) for smaller areas
    loop_search_space_resolution: 0.02        # finer resolution to improve matching in a compact space
    loop_search_space_smear_deviation: 0.05     # slight increase to allow for minor noise variations

    # (Optional) Coarse matching parameters – adjust if your environment is challenging:
    coarse_search_angle_offset: 0.349         # ~20° in radians
    coarse_angle_resolution: 0.0349           # ~2° in radians
    loop_match_minimum_response_coarse: 0.3

    ## Graph Optimization Settings
    optimization_period: 10.0                 # How frequently (in seconds) to run pose graph optimization
    optimizer_max_iterations: 20              # Maximum iterations for the pose graph optimizer per run
    constraint_search_space_time: 5.0         # Time window (in seconds) for considering loop closures

    use_adaptive_motion_thresholds: true   # Dynamically adjust thresholds based on velocity
