slam_toolbox:
  ros__parameters:
    # Robot frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # SLAM mode
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_timeout: 0.3
    update_timing: true
    publish_period: 0.25
    map_update_interval: 0.5
    max_update_rate: 10.0     # Reduced to ensure better scan processing

    # Map management - Tuned for accuracy
    resolution: 0.05
    max_laser_range: 8.0      # Reduced to avoid noisy long-range readings
    minimum_time_interval: 0.1 # More frequent updates
    transform_publish_period: 0.02

    # Processing parameters - Critical for map quality
    process_near_pose: true
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2    # Increased to reduce noise
    minimum_travel_heading: 0.2     # Increased to reduce noise
    scan_buffer_size: 5            # Reduced for more local accuracy
    scan_buffer_maximum_scan_distance: 5.0  # Reduced for better local matching
    link_match_minimum_response_fine: 0.8   # Much stricter matching
    link_scan_maximum_distance: 0.5         # Reduced for precise local mapping

    # Loop closure - Made very strict
    do_loop_closing: true
    loop_search_space: 2.0           # Smaller search space
    loop_match_minimum_chain_size: 10 # More strict chain matching
    loop_match_maximum_variance_coarse: 0.5  # Very strict variance
    loop_match_minimum_response_coarse: 0.7  # Higher threshold
    loop_match_minimum_response_fine: 0.8    # Higher threshold

    # Correlation parameters - Tuned for precision
    correlation_search_space_dimension: 0.1   # Smaller search space
    correlation_search_space_resolution: 0.01  # Higher resolution
    correlation_search_space_smear_deviation: 0.001 # Minimal smearing

    # Motion filter parameters - Very strict
    distance_variance_penalty: 2.0    # High penalty for motion variance
    angle_variance_penalty: 2.0       # High penalty for rotation variance
    fine_search_angle_offset: 0.001   # Very fine angle search

    # Rotation scoring - Critical for wall accuracy
    rotation_scoring_search_window: 30        # Larger window
    rotation_scoring_points_per_window: 15    # More points
    rotation_scoring_minimum_response: 0.3    # Higher threshold

    # Motion constraints - Limited for accuracy
    use_velocity_constraints: true
    use_acceleration_constraints: true
    max_velocity_linear: 0.5
    max_velocity_angular: 0.5     # Further reduced for better rotation accuracy
    max_acceleration_linear: 1.0   # Reduced for smoother motion
    max_acceleration_angular: 1.0  # Reduced for smoother rotation

    # Scan Matching Parameters - Fine-tuned for walls
    coarse_search_angle_offset: 0.05    # Much smaller angle steps
    coarse_angle_resolution: 0.002      # Very fine resolution
    
    # Additional Parameters
    use_adaptive_motion_thresholds: false  # Disabled for more consistent behavior
    matcher_threads: 1                     # Single thread for more deterministic results
    optimize_on_start: true
    
    # Optimization Settings
    optimization_period: 2.0              # More frequent optimization
    optimizer_max_iterations: 50          # More iterations for better convergence
    ceres_loss_function: "HUBER_LOSS"    # Better handling of outliers
