slam_toolbox:
  ros__parameters:
    # Robot frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # SLAM mode - Switch to localization mode if map is already built
    mode: mapping
    debug_logging: true  # Enable debug logging to diagnose issues
    throttle_scans: 1
    transform_timeout: 0.3
    update_timing: true
    publish_period: 0.25
    map_update_interval: 1.0  # Increased to reduce processing load
    max_update_rate: 5.0      # Reduced to ensure quality over speed

    # Map management - CRITICAL FOR DOUBLE WALLS
    resolution: 0.05
    max_laser_range: 6.0      # Further reduced to avoid noisy long-range readings
    minimum_time_interval: 0.5 # Increased to process fewer scans but more accurately
    transform_publish_period: 0.05 # Slightly slower but more stable

    # Processing parameters - FOCUSED ON WALL QUALITY
    process_near_pose: true
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.15    # Increased to reduce overlapping scans
    minimum_travel_heading: 0.15     # Increased to reduce scans during small rotations
    scan_buffer_size: 5              # Reduced for more consistent local mapping
    scan_buffer_maximum_scan_distance: 5.0  # Reduced scan distance
    link_match_minimum_response_fine: 0.6   # Increased for stricter matching
    link_scan_maximum_distance: 0.75        # Reduced for more precise local mapping

    # Loop closure - MADE MORE CONSERVATIVE
    do_loop_closing: true
    loop_search_space: 2.0           # Reduced search space further
    loop_match_minimum_chain_size: 10 # Increased for much stricter loop closure
    loop_match_maximum_variance_coarse: 0.5  # Reduced for very strict matching
    loop_match_minimum_response_coarse: 0.6  # Increased threshold
    loop_match_minimum_response_fine: 0.7    # Increased threshold

    # Correlation parameters - CRITICAL FOR DOUBLE WALLS
    correlation_search_space_dimension: 0.15  # Reduced for more precise search
    correlation_search_space_resolution: 0.01 # Balanced resolution
    correlation_search_space_smear_deviation: 0.005 # Minimized smearing

    # Motion filter parameters - INCREASED PENALTIES
    distance_variance_penalty: 2.0   # Increased penalty
    angle_variance_penalty: 3.0      # Significantly increased penalty
    fine_search_angle_offset: 0.001  # Very fine angle search

    # Rotation scoring - CRITICAL FOR TURNS
    rotation_scoring_search_window: 30        # Increased significantly
    rotation_scoring_points_per_window: 15    # Increased points per window
    rotation_scoring_minimum_response: 0.3    # Increased threshold

    # Motion constraints - TIGHTENED
    use_velocity_constraints: true
    use_acceleration_constraints: true
    max_velocity_linear: 0.3         # Reduced for more accurate mapping
    max_velocity_angular: 0.5        # Reduced angular velocity significantly
    max_acceleration_linear: 1.0     # Reduced for smoother motion
    max_acceleration_angular: 1.0    # Reduced for smoother rotation

    # Scan Matching Parameters - FINER RESOLUTION
    coarse_search_angle_offset: 0.05  # Reduced for finer search
    coarse_angle_resolution: 0.005    # Increased resolution significantly
    
    # Additional Parameters - SIMPLIFIED
    use_adaptive_motion_thresholds: true
    adaptive_threshold_coef: 1.0
    matcher_threads: 1               # Single thread for more consistent processing
    optimize_on_start: true
    enable_submaps: false            # Disabled submaps for simpler processing
    
    # Optimization Settings - MORE FREQUENT
    optimization_period: 3.0         # More frequent optimization
    optimizer_max_iterations: 50     # More iterations for better convergence
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"
    ceres_loss_function: "HUBER_LOSS"
    ceres_loss_function_parameter: 0.1  # Added for better outlier rejection

    # Additional critical parameters for double wall prevention
    map_start_pose: [0.0, 0.0, 0.0]  # Start with known pose
    map_start_at_dock: true          # Start mapping at a known position
    use_pose_extrapolator: false     # Disable pose extrapolation
    debug_logging: true              # Enable debug logging
    
    # Scan matching refinement
    refine_match_min_response: 0.7   # Very high threshold for refinement
    refine_near_angle_penalty: 0.5   # Penalty for angular deviation
    refine_far_angle_penalty: 1.0    # Higher penalty for larger deviations
