slam_toolbox:
  ros__parameters:
    # Robot frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # SLAM mode
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_timeout: 0.3    # increased from 0.2 to allow extra time for fast movements
    update_timing: true
    publish_period: 0.5
    map_update_interval: 1.0
    max_update_rate: 10.0

    # Map management
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05

    # Processing parameters
    process_near_pose: true
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.45
    link_scan_maximum_distance: 2.0

    # Loop closure parameters
    do_loop_closing: true
    loop_search_space: 8.0
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Motion filter parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 0.5
    fine_search_angle_offset: 0.00349

    # Increase these for better rotation stability
    rotation_scoring_search_window: 10
    rotation_scoring_points_per_window: 5
    rotation_scoring_minimum_response: 0.1

    # Add motion constraints
    use_velocity_constraints: true
    use_acceleration_constraints: true
    max_velocity_linear: 0.5
    max_velocity_angular: 1.0
    max_acceleration_linear: 1.0
    max_acceleration_angular: 1.0

    # (Optional) Coarse matching parameters – adjust if your environment is challenging:
    coarse_search_angle_offset: 0.349         # ~20° in radians
    coarse_angle_resolution: 0.0349           # ~2° in radians

    ## Graph Optimization Settings
    optimization_period: 10.0                 # How frequently (in seconds) to run pose graph optimization
    optimizer_max_iterations: 20              # Maximum iterations for the pose graph optimizer per run
    constraint_search_space_time: 5.0         # Time window (in seconds) for considering loop closures

    use_adaptive_motion_thresholds: true   # Dynamically adjust thresholds based on velocity
