slam_toolbox:
  ros__parameters:
    # Robot frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # SLAM mode
    mode: mapping
    debug_logging: true
    throttle_scans: 1

    # Map management
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    update_timing: true
    publish_period: 0.5
    map_update_interval: 1.0

    # Scan Matching
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1 